export {default as Home} from './Home/Home' 
export {default as Blog} from './Blog/Blog' 
export {default as About} from './About/About' 
export {default as Post} from './Post/Post' 
export {default as ErrorPage} from './ErrorPage/ErrorPage' 
export {default as SearchResults} from './SearchResults/SearchResults' 